name: CI
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: |
          echo "hello world"
          chmod +x ./setup.sh
          ./setup.sh
          echo "after running sh"
